server:
  port: 8010
spring:
  application:
    name: admin-service
  cloud:
    config:
      enabled: false

eureka:  #<1>
  instance:
    leaseRenewalIntervalInSeconds: 10
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761}/eureka/

management.security.enabled: false  #<2>

spring.boot.admin.routes.endpoints: env,metrics,dump,jolokia,info,configprops,trace,logfile,refresh,flyway,liquibase,heapdump,loggers,auditevents,hystrix.stream

spring.boot.admin.turbine:
  clusters: default
  location: turbine  #<1>
